spring:
  dubbo:
    application:
      name: "demo"
    registry:
      address: "192.168.244.201:2181"
      client: "curator"
      protocol: "zookeeper"
    protocol:
      name: "dubbo"
    provider:
      group: "demo"
      version: "1.0.0"